---
apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: gcmx
build:
  artifacts:
    - image: eu.gcr.io/gardener-project/gardener/gardener-custom-metrics
      ko:
        dependencies:
          paths:
            - cmd/**
            - example/**
            - pkg/**
            - vendor/**
            - VERSION
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd/gardener-custom-metrics
profiles:
  - name: debug
    activation:
      - command: debug
    manifests:
      rawYaml:
        - example/custom-metrics-deployment.yaml
#      kustomize:
#        paths:
#          - example/provider-local/seed-kind2/skaffold
    deploy:
      kubectl: {}

# TODO: Andrey: P1: cleanup
#    patches:
#      - op: add
#        path: /deploy/helm/releases/0/setValues
#        value:
#          replicaCount: 1
#          config.leaderElection.leaderElect: false
#          config.server.healthProbes.enable: false
#  - name: kind2
#    patches:
#      - op: add
#        path: /deploy/helm/releases/0/valuesFiles/-
#        value: example/gardener-local/gardenlet/values-kind2.yaml
#      - op: replace
#        path: /deploy/helm/hooks/after/0/host/command
#        value:
#          - bash
#          - -ec
#          - KUBECONFIG=$GARDENER_LOCAL_KUBECONFIG hack/usage/wait-for.sh seed local2 GardenletReady SeedSystemComponentsHealthy ExtensionsReady BackupBucketsReady
#  - name: extensions
#    patches:
#      - op: add
#        path: /deploy/helm/releases/0/valuesFiles/-
#        value: example/gardener-local/gardenlet/values-provider-extensions.yaml
#      - op: add
#        path: /deploy/helm/releases/0/valuesFiles/-
#        value: example/provider-extensions/gardenlet/{{.SEED_VALUES}}
#      - op: replace
#        path: /deploy/helm/hooks/after/0/host/command
#        value:
#          - bash
#          - -ec
#          - KUBECONFIG=$GARDENER_LOCAL_KUBECONFIG hack/usage/wait-for.sh seed "$SEED_NAME" GardenletReady SeedSystemComponentsHealthy ExtensionsReady
#  - name: ha-single-zone
#    patches:
#      - op: add
#        path: /deploy/helm/releases/0/valuesFiles/-
#        value: example/gardener-local/gardenlet/values-kind-ha-single-zone.yaml
#      - op: replace
#        path: /deploy/helm/hooks/after/0/host/command
#        value:
#          - bash
#          - -ec
#          - hack/usage/wait-for.sh seed local-ha-single-zone GardenletReady SeedSystemComponentsHealthy ExtensionsReady BackupBucketsReady
#  - name: kind2-ha-single-zone
#    patches:
#      - op: add
#        path: /deploy/helm/releases/0/valuesFiles/-
#        value: example/gardener-local/gardenlet/values-kind2-ha-single-zone.yaml
#      - op: replace
#        path: /deploy/helm/hooks/after/0/host/command
#        value:
#          - bash
#          - -ec
#          - KUBECONFIG=$GARDENER_LOCAL_KUBECONFIG hack/usage/wait-for.sh seed local2-ha-single-zone GardenletReady SeedSystemComponentsHealthy ExtensionsReady BackupBucketsReady
#  - name: ha-multi-zone
#    patches:
#      - op: add
#        path: /deploy/helm/releases/0/valuesFiles/-
#        value: example/gardener-local/gardenlet/values-kind-ha-multi-zone.yaml
#      - op: replace
#        path: /deploy/helm/hooks/after/0/host/command
#        value:
#          - bash
#          - -ec
#          - TIMEOUT=1200 hack/usage/wait-for.sh seed local-ha-multi-zone GardenletReady SeedSystemComponentsHealthy ExtensionsReady BackupBucketsReady
#  - name: ipv6
#    activation:
#      - env: IPFAMILY=ipv6
#    patches:
#      - op: add
#        path: /deploy/helm/releases/0/valuesFiles/-
#        value: example/gardener-local/gardenlet/values-ipv6.yaml
#  - name: debug
#    activation:
#      - command: debug
#    patches:
#      - op: add
#        path: /deploy/helm/releases/0/setValues
#        value:
#          replicaCount: 1
#          config.leaderElection.leaderElect: false
#          config.server.healthProbes.enable: false
